
server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://192.168.2.67:3306/security
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true





